# Custom Language File for Launcher Customizer

[ejs.app]
title = "Waktaverse Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/DOS0313/WaktaverseLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "왁닝맨"
welcomeDescription = """해당 런처는 "왁닝맨 : 경천역 보물레이스"를 진행하기 위한 모드 및 설정을 자동으로 진행해주는 커스텀 런처입니다."""
welcomeDescCTA = "서버 지원 : Waktaverse Games"
